spring:
  application:
    name: Loan-Application
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/3nesh
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: 'off'
  security:
    user:
      name: user
      password: 1111